### ISSUE TITLE
"adapter not found" on manjaro

### ISSUE THREAD

**Issue by makerio90** [stylesuxx/amdvbflash#2]
trying to update bios using [this](https://andrealmeid.com/post/2020-05-01-vbios2/) tutorial
```bash
$ sudo amdvbflash -ai
AMDVBFLASH version 4.71, Copyright (c) 2020 Advanced Micro Devices, Inc.

Adapter not found
```
i checked and my card is on `0000:2c:00.0` but its not found? on linux515

lmk what else i need to put here :/

**Comment by stylesuxx** [comment]
Well, then it is probably not supported by this tool. This is just a mirror of a leaked bin. I can not give you any kind of support here.
